---
apiVersion: v1
kind: Service
metadata:
  name: sedaro-demo-web
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
      nodePort: {{ .Values.web.nodePort }}
