---
apiVersion: v1
kind: Service
metadata:
  name: sedaro-nano-app
spec:
  selector:
    app: app
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
